name: My_ECS_Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          AWS_REGION: ap-south-1
          ECR_REPO_URI: 656982906157.dkr.ecr.ap-south-1.amazonaws.com/myrepo
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REPO_URI:$IMAGE_TAG .
          docker push $ECR_REPO_URI:$IMAGE_TAG

      - name: Update ECS service
        env:
          AWS_REGION: ap-south-1
          CLUSTER_NAME: Cluster
          SERVICE_NAME: myservice
          ECR_REPO_URI: 656982906157.dkr.ecr.ap-south-1.amazonaws.com/myrepo
          IMAGE_TAG: latest
        run: |
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment --output json